live_config_reload = true
working_directory = "/Users/lemon/Projects"

[window]
decorations = "none"
dynamic_padding = true

[font]
size = 20
offset.y = 8
normal = { family = "CommitMono" }

[shell]
program = "/opt/homebrew/bin/fish"
args = ["-l", "-c", "tmux attach || tmux"]


# Default colors
[colors.primary]
background = '0x1b1e28'
foreground = '0xa6accd'

# Normal colors
[colors.normal]
black = "0x1b1e28"
red = "0xd0679d"
green = "0x5de4c7"
yellow = "0xfffac2"
blue = "0x89ddff"
magenta = "0xfcc5e9"
cyan = "0xadd7ff"
white = "0xffffff"

# Bright colors
[colors.bright]
black = "0xa6accd"
red = "0xd0679d"
green = "0x5de4c7"
yellow = "0xfffac2"
blue = "0xadd7ff"
magenta = "0xfae4fc"
cyan = "0x89ddff"
white = "0xffffff"
